### ISSUE TITLE
ML Inference on Raspberry Pi requires 2.5 A power source

### ISSUE THREAD

**Issue by rddefauw** [awsdocs/aws-greengrass-developer-guide#10]
The [inference instructions](https://docs.aws.amazon.com/greengrass/latest/developerguide/ml-console.html) should note that running deep learning frameworks on a Raspberry Pi requires a 2.5A power source.  If you use a lower rated power supply, the Pi will likely reboot whenever you try to perform inference by running the `forward` method on the network, at least for deep networks that you see with image use cases.  I saw this behavior with MxNet, the DLR, and TensorFlow on a Pi 3B+.

**Comment by dkdiaz** [comment]
Thank you for your input @rddefauw ! We'll add this information to the inference instructions.
