### ISSUE TITLE
aws iot greengrass on jetson nano - local resource access failed

### ISSUE THREAD

**Issue by varun-tangoit** [awsdocs/aws-greengrass-developer-guide#12]
Hi,

I'm trying to implement aws greengrass on jetson nano  I'm following below aws documentation;
https://docs.aws.amazon.com/greengrass/latest/developerguide/lra-console.html

But i can't able to proceed or having issue read/write a file from cloud to edge. Im having spending more a days, didn't find and can't able fix this issue. Please help me out!!!
Here is my log while lambda running;

```
[2019-07-01T15:57:47.009+05:30][INFO]-lambda_runtime.py:331,Caught signal 15. Stopping runtime.
[2019-07-01T15:57:59.286+05:30][INFO]-lambda_runtime.py:114,Running [arn:aws:lambda:us-east-1:xxxxxxxxxx:function:TestLRA:7]
[2019-07-01T15:57:59.286+05:30][INFO]-ipc_client.py:170,Getting work for function [arn:aws:lambda:us-east-1:xxxxxxxxxxx:function:TestLRA:7] from http://localhost:8000/2016-11-01/functions/arn:aws:lambda:us-east-1:xxxxxxxxxxx:function:TestLRA:7/work

```

**Comment by dkdiaz** [comment]
Hi @varun-tangoit . Sorry that you're having trouble! I went through the tutorial (using a Raspberry Pi) to try to reproduce, but it seems to be working in general. 

Can you please open an issue in the AWS IoT Greengrass forum (https://forums.aws.amazon.com/forum.jspa?forumID=254)? The Greengrass support team should be able to help you troubleshoot this problem.

They'll want to know which version of the AWS IoT Greengrass software you're running. You can find it by running the following command from the `/greengrass/ggc/core` directory:
`sudo ./greengrassd --version`

**Comment by varun-tangoit** [comment]
@dkdiaz sure will do that. Yes i have posted, i have mentioned below thread url;
https://forums.aws.amazon.com/thread.jspa?threadID=305715. Please help me out!
and I have few doubt or give me some suggestion,
* is it possible to add bulk number of files from cloud to edge?
*  is it possible to get status of system services and remotely stop/start system systems?
*  is it possible to get system memory usage/storage space etc information?

**Comment by dkdiaz** [comment]
Hi @varun-tangoit Thank you for the reply. We'll watch your post to see if we should update the documentation. 
These are also good questions to ask in the forum. The Greengrass team should be able to say whether your specific uses cases are supported and give information about how to implement them.

**Comment by varun-tangoit** [comment]
Hi @dkdiaz. Thanks. sure. kindly help me out from this issue or give me some suggestion on this forum.

**Comment by dkdiaz** [comment]
Hi @varun-tangoit I'm sorry, but this is outside my area of expertise. The AWS IoT Greengrass forum (https://forums.aws.amazon.com/forum.jspa?forumID=254) is the best place to ask technical questions. They can help troubleshoot your problem and give more information about your use cases.

**Comment by varun-tangoit** [comment]
Hi @dkdiaz I mentioned runtime.log and group.json and other configuration in this existing fourm. Yeah I have few more improvement; i need to know why s3 bucket files can't able to download to respective edge device. Here is my log;
[2019-07-04T01:59:16.751+05:30][DEBUG]-retry.py:211,Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0, status=None)
[2019-07-04T01:59:16.751+05:30][DEBUG]-connectionpool.py:815,Starting new HTTPS connection (1): <bucket_name>.s3.amazonaws.com:443

**Comment by varun-tangoit** [comment]
Thnks @dkdiaz for support. issue has been resolved.

**Comment by dkdiaz** [comment]
Great, thanks for your interest in Greengrass, @varun-tangoit !
