### ISSUE TITLE
Got a not supported error on a pi-zero but was able to install manually

### ISSUE THREAD

**Issue by jdemuth** [awsdocs/aws-greengrass-developer-guide#13]
Code 1, Message: Platform Linux-4.19.75+-armv6l-with-debian-10.1 not supported

**Comment by dkdiaz** [comment]
Hi @jdemuth - Thanks for reporting this issue. Will forward it to the Greengrass team to investigate.

**Comment by MikeDombo** [comment]
Where did you see that code? What program were you running?

**Comment by MikeDombo** [comment]
At this time, the Greengrass Device Setup does not work with pizero, however we are working to make it compatible.

**Comment by dkdiaz** [comment]
Thanks again for reporting the issue, @jdemuth !
