### ISSUE TITLE
The greengrass:Discover permission is not included in the example policy

### ISSUE THREAD

**Issue by kennu** [awsdocs/aws-greengrass-developer-guide#19]
We spent a lot of time debugging why our IoT policy, based on the "minimal AWS IoT Policy for Greengrass" (https://github.com/awsdocs/aws-greengrass-developer-guide/blob/master/doc_source/device-auth.md) did not allow our Docker services to discover the Greengrass endpoint.

The reason turned out to be that **greengrass:Discover** is not included in the minimal example policy. It includes **greengrass:GetConnectivityInfo**, so we thought that would be enough to allow the services to perform discovery. We completely missed that **greengrass:Discover** was even mentioned in the documentation.

Since many developers probably copy and adapt the example policy, I would suggest either adding the **greengrass:Discover** permission to it, or at least adding a note reminding that you will also need **greengrass:Discover** if you want to perform discovery.

Note that we are using a shared IoT policy that covers both our Greengrass Core and the Docker services running as "devices" in the Greengrass Group. I don't know if this is a normal use case, but we certainly don't want to create even more separate IoT policies for all the Docker containers running on every device.

PS. To add some difficulty, **greengrass:Discover** is also not included in this documentation: https://docs.aws.amazon.com/IAM/latest/UserGuide/list_awsiotgreengrass.html#awsiotgreengrass-actions-as-permissions. So it's pretty difficult to spot it when you don't even realize it exists.

**Comment by dkdiaz** [comment]
Thanks for the feedback, @kennu - and sorry that this information was hard to find. We'll look into the missing permission in the IAM guide and include or note that **greengrass:Discover** is required in IoT policies to allow devices to connect to/discover the core, as you suggest.

**Comment by dkdiaz** [comment]
Resolving this issue. The note was added to the docs and the permission update is in the pipeline. Thanks again @kennu !
