### ISSUE TITLE
Docs for IoT Lambda/Greengrass out of date

### ISSUE THREAD

**Issue by gherlein** [awsdocs/aws-greengrass-developer-guide#22]
https://docs.aws.amazon.com/greengrass/latest/developerguide/config-lambda.html

"In the AWS IoT console, under Greengrass, choose Groups, and then choose the group that you created in Module 2."

There is no Groups - the entries are:

Getting started
Core devices
Components
Deployments

Under Manage there is Thing Groups, but there is no way to add a Lamba.  Even under Actions.

The docs seem very much out of date with the actual web UI.

**Comment by feiyxAWS** [comment]
Hello, 

Thanks for your feedback on our documentation. 

This guide is used for AWS IoT Greenrgrass Version 1. In the AWS IoT console,  under **Greengrass**, choose **Classic (V1)**,  and then choose **Groups**. 

For more information about AWS IoT Greengrass Version 2, see the [Developer Guide, Version 2](https://docs.aws.amazon.com/greengrass/v2/developerguide/what-is-iot-greengrass.html). 

Let me know if you need more information. 

Sincerely,
 
Feiyi Xu

**Comment by gherlein** [comment]
Version 1 needs to be MUCH MORE CLEARLY marked as being deprecated in favor of v2.  I am not sure how I arrived at v1 instructions after installing V2, but it was not at all obvious.  It should be.  Having two versions there with only tiny type in the upper left corner to tell the difference does not clearly help the customer

**Comment by richa-aws** [comment]
Thanks for taking the time to provide this feedback! I've added it to the team's list of items for future consideration for both the V1 and V2 documentation. 

Best,
Richa Mehta
