### ISSUE TITLE
Where can I download the lambda function 

### ISSUE THREAD

**Issue by gsjoy8888** [awsdocs/aws-greengrass-developer-guide#5]
It seems the lambda function greengrassObjectClassification is missing from this tutorial

**Comment by dkdiaz** [comment]
Hi @gsjoy8888 . The Python file is now in this directory in the download package: 
ggc-mxnet-v1.2.1-python-raspi.tar.gz\ggc-mxnet-v1.2.1-python-raspi.tar\ggc-mxnet-v1.2.1-python-raspi\greengrass-ml-squeezenet-object-classification-raspi-python.tar.gz\greengrass-ml-squeezenet-object-classification-raspi-python.tar\greengrass-ml-squeezenet-object-classification-raspi-python\

Thanks for reporting this issue!

**Comment by dkdiaz** [comment]
The framework installation generates the Lambda deployment package, which contains the greengrassObjectClassification py file. Clarified this in the docs.
