### ISSUE TITLE
greengrass is not authorized to assume the service role associated with this account

### ISSUE THREAD

**Issue by cpaterop** [awsdocs/aws-greengrass-developer-guide#7]
Hi Guys,
when trying to follow your instructions and after trying to deploying the group rule i get the above message.. any clue how to overcome it?
kind regards,
Christos

**Comment by dkdiaz** [comment]
Hi @cpaterop . Can you please check if the Greengrass service role is associated with your AWS account in the current region? Steps are in this topic: https://docs.aws.amazon.com/greengrass/latest/developerguide/service-role.html

**Comment by cpaterop** [comment]
thnanks:) that helped. i had to do it in linux though since th windows command was giving me some errors:)
